name: Terraform CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
    
  workflow_dispatch:
    inputs:
      eks-name:
        description: EKS name
        required: true
        default: 'eks-demo'
        type: string

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply # change Apply to Destroy or vice versa as needed
      run: terraform apply -auto-approve # change apply to destroy or vice versa as needed
      env:
        TF_VAR_ec2_name:  "${{ github.event.inputs.eks-name }}"
    